### ISSUE TITLE
spotify speaker dead error handling

### ISSUE THREAD

**Issue by M1chaCH** [M1chaCH/room-automation#5]
this error occured after i've tried to start a scene with audio and my spotify speaker was completely offline. (the hardware device was turned off)

[speakerDeadError.txt](https://github.com/M1chaCH/room-automation/files/11847729/speakerDeadError.txt)

**Comment by M1chaCH** [comment]
Thread[helidon-server-14,5,server] [2023-07-24 19:28:29] [INFO] RequestFilter -> received request to POST:/automation/scene/2?audio=true
Thread[helidon-server-14,5,server] [2023-07-24 19:28:29] [INFO] LightConfigProvider -> selected 2 light_configurations
Thread[helidon-server-14,5,server] [2023-07-24 19:28:29] [INFO] SceneProvider -> successfully loaded 3 device_light_configurations
Thread[helidon-server-14,5,server] [2023-07-24 19:28:29] [INFO] SceneService -> applying scene 2-focus, including audio:true
Thread[helidon-server-14,5,server] [2023-07-24 19:28:29] [INFO] LightConnectionVerifier -> light connection expired
Thread[helidon-server-14,5,server] [2023-07-24 19:28:29] [INFO] YeelightDeviceProvider -> selected 3 yeelight_devices
Thread[helidon-server-14,5,server] [2023-07-24 19:28:29] [INFO] YeelightDeviceService$Proxy$_$$_WeldSubclass -> successfully connected to device at 192.168.50.200
Thread[helidon-server-14,5,server] [2023-07-24 19:28:29] [INFO] YeelightDeviceService$Proxy$_$$_WeldSubclass -> successfully connected to device at 192.168.50.201
Thread[helidon-server-14,5,server] [2023-07-24 19:28:29] [INFO] YeelightDeviceService$Proxy$_$$_WeldSubclass -> successfully connected to device at 192.168.50.202
Thread[helidon-server-14,5,server] [2023-07-24 19:28:29] [INFO] YeelightDeviceService$Proxy$_$$_WeldSubclass -> connected to 3 devices & found 0 offline devices
Thread[helidon-server-14,5,server] [2023-07-24 19:28:29] [INFO] YeelightDeviceService$Proxy$_$$_WeldSubclass -> applied config to light: [ light:192.168.50.202-wall | color:r-120 g-255 b-194 | brightness:75 ] }
Thread[helidon-server-14,5,server] [2023-07-24 19:28:30] [INFO] YeelightDeviceService$Proxy$_$$_WeldSubclass -> applied config to light: [ light:192.168.50.200-desk | color:r-120 g-255 b-194 | brightness:75 ] }
Thread[helidon-server-14,5,server] [2023-07-24 19:28:30] [INFO] YeelightDeviceService$Proxy$_$$_WeldSubclass -> applied config to light: [ light:192.168.50.201-bed | color:r-179 g-242 b-255 | brightness:100 ] }
Thread[helidon-server-14,5,server] [2023-07-24 19:28:30] [INFO] SpotifyApiWrapper$Proxy$_$$_WeldSubclass -> setting playback volume to 30
Thread[helidon-server-14,5,server] [2023-07-24 19:28:30] [SEVERE] RuntimeExceptionMapper -> got UNKNOWN internal server error!
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:1186)
	at java.base/java.util.Map.of(Map.java:1373)
	at ch.micha.automation.room.spotify.SpotifyApiWrapper.setPlaybackVolume(SpotifyApiWrapper.java:349)
	at ch.micha.automation.room.spotify.SpotifyApiWrapper$Proxy$_$$_WeldSubclass.setPlaybackVolume$$super(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
	at ch.micha.automation.room.spotify.interceptor.SpotifyAuthorisationInterceptor.intercept(SpotifyAuthorisationInterceptor.java:29)
	at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at ch.micha.automation.room.spotify.SpotifyApiWrapper$Proxy$_$$_WeldSubclass.setPlaybackVolume(Unknown Source)
	at ch.micha.automation.room.spotify.SpotifyApiWrapper$Proxy$_$$_WeldClientProxy.setPlaybackVolume(Unknown Source)
	at ch.micha.automation.room.spotify.SpotifyService.startContext(SpotifyService.java:64)
	at ch.micha.automation.room.spotify.SpotifyService$Proxy$_$$_WeldClientProxy.startContext(Unknown Source)
	at ch.micha.automation.room.scene.SceneService.applyScene(SceneService.java:72)
	at ch.micha.automation.room.scene.SceneService.applyScene(SceneService.java:47)
	at ch.micha.automation.room.scene.SceneService$Proxy$_$$_WeldClientProxy.applyScene(Unknown Source)
	at ch.micha.automation.room.scene.SceneResource.applyScene(SceneResource.java:71)
	at ch.micha.automation.room.scene.SceneResource$Proxy$_$$_WeldClientProxy.applyScene(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$6(JerseySupport.java:339)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Thread[helidon-server-14,5,server] [2023-07-24 19:28:30] [INFO] ResponseFilter -> responding to POST:/automation/scene/2 with 500 - Internal Server Error after 893ms
Thread[helidon-server-9,5,server] [2023-07-24 19:29:50] [INFO] RequestFilter -> received request to GET:/automation/spotify/client?
Thread[helidon-server-9,5,server] [2023-07-24 19:29:50] [INFO] ResponseFilter -> responding to GET:/automation/spotify/client with 200 - OK after 1ms
Thread[helidon-websocket-8,5,helidon-websocket-thread-pool-1] [2023-07-24 19:29:50] [INFO] AlarmNotificationService -> Alarm message listener connected: 5cbc076d-0de1-44e2-bb85-e6b9c86be4a6
Thread[helidon-websocket-10,5,helidon-websocket-thread-pool-1] [2023-07-24 19:29:55] [INFO] AlarmNotificationService -> disconnected Alarm message listener: 5cbc076d-0de1-44e2-bb85-e6b9c86be4a6
Thread[helidon-server-1,5,server] [2023-07-24 19:29:55] [INFO] RequestFilter -> received request to GET:/automation/spotify/client?
Thread[helidon-server-1,5,server] [2023-07-24 19:29:55] [INFO] ResponseFilter -> responding to GET:/automation/spotify/client with 200 - OK after 1ms
Thread[helidon-websocket-2,5,helidon-websocket-thread-pool-1] [2023-07-24 19:29:55] [INFO] AlarmNotificationService -> Alarm message listener connected: bba37a7b-b94e-485f-a0a1-a623a0b44b3d
Thread[helidon-server-10,5,server] [2023-07-24 19:29:56] [INFO] RequestFilter -> received request to GET:/automation/spotify?
Thread[helidon-server-10,5,server] [2023-07-24 19:29:56] [INFO] ResponseFilter -> responding to GET:/automation/spotify with 204 - No Content after 1ms
Thread[helidon-server-2,5,server] [2023-07-24 19:29:56] [INFO] RequestFilter -> received request to GET:/automation/spotify/player?
Thread[helidon-server-2,5,server] [2023-07-24 19:29:56] [INFO] SpotifyApiWrapper$Proxy$_$$_WeldSubclass -> loading current spotify player
Thread[helidon-server-15,5,server] [2023-07-24 19:29:56] [INFO] RequestFilter -> received request to GET:/automation/spotify/resources?
Thread[helidon-server-15,5,server] [2023-07-24 19:29:56] [INFO] SpotifyApiWrapper$Proxy$_$$_WeldSubclass -> loading first 50 saved playlists from spotify
Thread[helidon-server-2,5,server] [2023-07-24 19:29:56] [INFO] SpotifyApiWrapper$Proxy$_$$_WeldSubclass -> successfully fetched spotify player
Thread[helidon-server-2,5,server] [2023-07-24 19:29:56] [INFO] ResponseFilter -> responding to GET:/automation/spotify/player with 200 - OK after 182ms
Thread[helidon-server-15,5,server] [2023-07-24 19:29:56] [INFO] SpotifyApiWrapper$Proxy$_$$_WeldSubclass -> successfully loaded 47 playlists
Thread[helidon-server-15,5,server] [2023-07-24 19:29:56] [INFO] ResponseFilter -> responding to GET:/automation/spotify/resources with 200 - OK after 249ms
Thread[helidon-server-12,5,server] [2023-07-24 19:29:58] [INFO] RequestFilter -> received request to PUT:/automation/spotify/playback?
Thread[helidon-server-12,5,server] [2023-07-24 19:29:58] [INFO] SpotifyApiWrapper$Proxy$_$$_WeldSubclass -> loading playback state of current player
Thread[helidon-server-12,5,server] [2023-07-24 19:29:58] [INFO] SpotifyApiWrapper$Proxy$_$$_WeldSubclass -> pausing playback of default device
Thread[helidon-server-12,5,server] [2023-07-24 19:29:58] [INFO] SpotifyApiWrapper$Proxy$_$$_WeldSubclass -> successfully paused playback
Thread[helidon-server-12,5,server] [2023-07-24 19:29:58] [INFO] ResponseFilter -> responding to PUT:/automation/spotify/playback with 204 - No Content after 193ms
Thread[helidon-server-16,5,server] [2023-07-24 19:29:59] [INFO] RequestFilter -> received request to PUT:/automation/spotify/playback?
Thread[helidon-server-16,5,server] [2023-07-24 19:29:59] [INFO] SpotifyApiWrapper$Proxy$_$$_WeldSubclass -> loading playback state of current player
Thread[helidon-server-16,5,server] [2023-07-24 19:29:59] [INFO] SpotifyApiWrapper$Proxy$_$$_WeldSubclass -> resuming playback
Thread[helidon-server-16,5,server] [2023-07-24 19:29:59] [SEVERE] RuntimeExceptionMapper -> got UNKNOWN internal server error!
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.ImmutableCollections$Map1.<init>(ImmutableCollections.java:1105)
	at java.base/java.util.Map.of(Map.java:1353)
	at ch.micha.automation.room.spotify.SpotifyApiWrapper.resumePlayback(SpotifyApiWrapper.java:309)
	at ch.micha.automation.room.spotify.SpotifyApiWrapper$Proxy$_$$_WeldSubclass.resumePlayback$$super(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
	at ch.micha.automation.room.spotify.interceptor.SpotifyAuthorisationInterceptor.intercept(SpotifyAuthorisationInterceptor.java:29)
	at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at ch.micha.automation.room.spotify.SpotifyApiWrapper$Proxy$_$$_WeldSubclass.resumePlayback(Unknown Source)
	at ch.micha.automation.room.spotify.SpotifyApiWrapper$Proxy$_$$_WeldClientProxy.resumePlayback(Unknown Source)
	at ch.micha.automation.room.spotify.SpotifyService.togglePlayback(SpotifyService.java:56)
	at ch.micha.automation.room.spotify.SpotifyService$Proxy$_$$_WeldClientProxy.togglePlayback(Unknown Source)
	at ch.micha.automation.room.spotify.SpotifyResource.togglePlayback(SpotifyResource.java:62)
	at ch.micha.automation.room.spotify.SpotifyResource$Proxy$_$$_WeldClientProxy.togglePlayback(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$6(JerseySupport.java:339)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Thread[helidon-server-16,5,server] [2023-07-24 19:29:59] [INFO] ResponseFilter -> responding to PUT:/automation/spotify/playback with 500 - Internal Server Error after 127ms

**Comment by M1chaCH** [comment]
this time here, i was listening to music, pausing in the UI -> resuming in the UI 10 seconds later and I get this nullpointer. 
for some reason I think the SpotifyApiWrapper loses the value of the field deviceId. (i am 100% sure that deviceId being null is the reason for this nullpointer)

(restarting the container solves the issue)
