### ISSUE TITLE
long running device connection

### ISSUE THREAD

**Issue by M1chaCH** [M1chaCH/room-automation#6]
the system ran now for 10 days and I did not face any issues until now. I can't get any device connections any more:

```logs
Thread[helidon-server-11,5,server] [2023-07-03 16:20:14] [INFO] RequestFilter -> received request to GET:/automation/device?includeState=true
Thread[helidon-server-11,5,server] [2023-07-03 16:20:14] [SEVERE] AppExceptionMapper -> got internal server error
ch.micha.automation.room.errorhandling.exceptions.UnexpectedYeeLightException: unexpected yeelight exception ond device: 192.168.50.200
        at ch.micha.automation.room.light.yeelight.YeelightDeviceService.loadConfig(YeelightDeviceService.java:268)
        at ch.micha.automation.room.light.yeelight.YeelightDeviceService.lambda$loadCurrentOnlineConfigs$0(YeelightDeviceService.java:128)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at ch.micha.automation.room.light.yeelight.YeelightDeviceService.loadCurrentOnlineConfigs(YeelightDeviceService.java:128)
        at ch.micha.automation.room.light.yeelight.YeelightDeviceService$Proxy$_$$_WeldSubclass.loadCurrentOnlineConfigs(Unknown Source)
        at ch.micha.automation.room.light.yeelight.YeelightDeviceService.getAllDevicesWithState(YeelightDeviceService.java:144)
        at ch.micha.automation.room.light.yeelight.YeelightDeviceService$Proxy$_$$_WeldSubclass.getAllDevicesWithState$$super(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
        at ch.micha.automation.room.light.yeelight.interceptor.LightConnectionVerifier.intercept(LightConnectionVerifier.java:38)
        at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
        at ch.micha.automation.room.light.yeelight.YeelightDeviceService$Proxy$_$$_WeldSubclass.getAllDevicesWithState(Unknown Source)
        at ch.micha.automation.room.light.yeelight.YeelightDeviceService$Proxy$_$$_WeldClientProxy.getAllDevicesWithState(Unknown Source)
        at ch.micha.automation.room.light.yeelight.YeelightDeviceResource.getStoredDevices(YeelightDeviceResource.java:28)
        at ch.micha.automation.room.light.yeelight.YeelightDeviceResource$Proxy$_$$_WeldClientProxy.getStoredDevices(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
        at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$4(JerseySupport.java:335)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
        at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.mollin.yapi.exception.YeelightSocketException: java.net.SocketException: Broken pipe
        at com.mollin.yapi.socket.YeelightSocketHolder.send(YeelightSocketHolder.java:82)
        at com.mollin.yapi.YeelightDevice.sendCommand(YeelightDevice.java:120)
        at com.mollin.yapi.YeelightDevice.getProperties(YeelightDevice.java:135)
        at ch.micha.automation.room.light.yeelight.YeelightDeviceService.loadConfig(YeelightDeviceService.java:244)
        ... 53 more
Caused by: java.net.SocketException: Broken pipe
        at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
        at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
        at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
        at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
        at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
        at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
        at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:318)
        at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:160)
        at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248)
        at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:257)
        at com.mollin.yapi.socket.YeelightSocketHolder.send(YeelightSocketHolder.java:80)
        ... 56 more

Thread[helidon-server-11,5,server] [2023-07-03 16:20:14] [INFO] ResponseFilter -> responding to GET:/automation/device with 500 - Internal Server Error after 2ms
```

need to investigate and handle this error.

**Comment by M1chaCH** [comment]
obviously restarting temporarily solved the issue.
